### ISSUE TITLE
How do I add custom styling to the rendered document?

### ISSUE THREAD

**Issue by isaac-weisberg** [PeterWone/vsc-print#122] opened 2021-12-02 08:57 UTC

**Comment by isaac-weisberg** [comment] 2021-12-02 09:05
Huh... something must be wrong, I have changed the styles in the extension settings, but the paper is still style-free. There default tables, default font changes and it doesn't look good, it's bland.

Why do you think my styles aren't applied?

**Comment by PeterWone** [comment] 2021-12-02 09:08
I was in the process of referring you to those settings. If they don't work for you something is wrong. I am testing it now. Something else you can do is supply a CSS stylesheet. Look in the manual near the end where it tells you how to add the stylesheet for Katex. You can add any number of stylesheets there and they should take effect.

**Comment by isaac-weisberg** [comment] 2021-12-02 09:12
![image](https://user-images.githubusercontent.com/36449887/144392075-da0121c7-8cb0-45f9-a3fc-460704fc2c9a.png)
I was wondering if there is an issue with a big document that I was trying to print and I have created a smaller one, but to no avail...

**Comment by isaac-weisberg** [comment] 2021-12-02 09:20
I have tried to switch to Safari from Chrome, and I have put this into my Alternative Browser Path:
```
/Applications/Safari.app/Contents/MacOS/Safari
```

Unfortunately, printing results with Safari erroring out with:
![safari?](https://user-images.githubusercontent.com/36449887/144393402-fb7a20b1-e253-406d-a107-765cb0c03db9.jpg)

**Comment by PeterWone** [comment] 2021-12-02 09:21
Don't use Safari, Chrome is the most tested choice.

**Comment by isaac-weisberg** [comment] 2021-12-02 09:23
Source that I'm trying to print, just in case
```
# Hello, my name is Steven McDingles

## Installation
You cannot install this software because it doesn't work, like, we haven't even--
```ruby
pod 'CookyBooky'
```
```

**Comment by PeterWone** [comment] 2021-12-02 09:26
I made this up from your sample

```
# Hello, my name is Steven McDingles

## Installation

You cannot install this software because it doesn't work, like we haven't even--

```
pod 'CookyBooky'
```

Head1|Head2
-|-
Cell2|Cell2
```
Then I change the settings like this
![image](https://user-images.githubusercontent.com/5498936/144394115-314ebe62-cff6-4b1b-841e-9522bd846875.png)

and printed

![image](https://user-images.githubusercontent.com/5498936/144394267-a0a1a5bc-4452-4874-8d1e-3535963af140.png)

**Comment by PeterWone** [comment] 2021-12-02 09:28
Now with Blackadder headings

![image](https://user-images.githubusercontent.com/5498936/144394721-70c5ab0f-0e7f-4039-90ee-7e219a03f6ce.png)

**Comment by isaac-weisberg** [comment] 2021-12-02 09:31
Yeah, actually these styles do work, it's just the themes are not applied...

**Comment by PeterWone** [comment] 2021-12-02 09:31
Oh, check carefully what you put in those style settings, it has to be valid CSS and it's pretty snippy about syntax.

**Comment by PeterWone** [comment] 2021-12-02 09:33
Themes? Are you talking about this?
![image](https://user-images.githubusercontent.com/5498936/144395428-52e1e5d4-448e-41b2-adee-29e345047235.png)

**Comment by isaac-weisberg** [comment] 2021-12-02 09:33
> Oh, check carefully what you put in those style settings, it has to be valid CSS and it's pretty snippy about syntax.
Yeah, I didn't change anything

> OK lets start with your platform.
```
Version: 1.62.3 (Universal)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T07:59:13.865Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.4.0
```

**Comment by isaac-weisberg** [comment] 2021-12-02 09:34
> Themes? Are you talking about this?

 Yeah :) What, they don't actually do what I think they do? :)

**Comment by PeterWone** [comment] 2021-12-02 09:35
Those apply to syntax colouring of source code. They don't affect Markdown.

**Comment by PeterWone** [comment] 2021-12-02 09:35
So it appears you've found several problems... with the manual. I admit it needs a lot of work the extension has grown considerably over the last year.

**Comment by PeterWone** [comment] 2021-12-02 09:37
Thank you for bringing it up with me instead of just taking a dump on it in a review.

**Comment by isaac-weisberg** [comment] 2021-12-02 09:39
>Those apply to syntax colouring of source code. They don't affect Markdown.

Oh I should've read better then :) Thank you, so essentially, the result that I was getting actually IS the expected behavior - oh my lord, so I should configure the styling myself, great :) Thank you

> with the manual.
Nah, honest to god, in a typical hurrying user fashion I have been skimming through the documents without diving deeper and reading properly, so it's genuinely my fault.

**Comment by PeterWone** [comment] 2021-12-02 09:39
If you can quantify how you hoped a theme would apply to a Markdown document, feel free to raise an issue and I'll look at how hard it is to give you what you want. In the meantime I think we've got to the bottom of your confusion here, so if you feel _this_ issue is resolved please close it.

**Comment by PeterWone** [comment] 2021-12-02 09:41
It is the way it is so that styling for source code and styling for documents are independent and don't interfere.

**Comment by isaac-weisberg** [comment] 2021-12-02 09:42
Wait, but, ugh... I wonder if, does this mean that there is no code highlighting in the rendered markdown by default?
Is there a way to configure code highlighting?

**Comment by PeterWone** [comment] 2021-12-02 09:43
Oh you mean when you put code in markdown inside a fence... interesting. Let me play with that. I can see why you care.

**Comment by PeterWone** [comment] 2021-12-02 09:47
ok the answer is you get whatever the baked in markdown render pipeline does... except you don't. In the preview it's syntax coloured and in the browser it isn't. Since the HTML is generated by the SAME pipeline that means there's some CSS gone walkabout mostly because I never tested this case. Leave this open, it's a bug.

**Comment by PeterWone** [comment] 2021-12-02 09:50
It's not a severe bug. In the settings uncheck Print and Close and then print your ruby again. It will get sent to the browser but the print dialog won't pop and you can rummage in the document to find the names of the styles on the bits that are coloured in preview. If you define the missing classes in a CSS file and add it to your stylesheets you should start getting syntax colouring in your markdown code blocks.

**Comment by PeterWone** [comment] 2021-12-02 10:13
![image](https://user-images.githubusercontent.com/5498936/144402092-c7d9cd8c-a553-4b27-b9de-34a0182ac01a.png)

Next release.

**Comment by PeterWone** [comment] 2021-12-02 10:22
If anyone asks for syntax colouring on raw Markdown inside a code fence in Markdown I'm going to scream.

**Comment by isaac-weisberg** [comment] 2021-12-02 14:13
Hmmm it renders a bunch of `hljs-title`, `hljs-keyword`, and so on, CSS classes. As well as an entire `code` DOM element, which is interesting.

But I would like not to have to specify these classes manually. You said something about next release - do you mean that next release the styling will work properly on its own?

**Comment by PeterWone** [comment] 2021-12-02 14:18
Oh I'm sorry, I should have been more explicit. Yes, I've fixed it. The only reason I haven't pushed out an update is I'm in the middle of rewriting my CICD scripts. If you know how to build an extension yourself I can push the change to the repo and you can get the fix immediately, otherwise you'll have to wait for me to work though all the BS associated with publishing an update to the marketplace.

**Comment by isaac-weisberg** [comment] 2021-12-02 14:23
I'll just wait for the fix - and thank you fixing it at all, that's pretty cool of you :)

**Comment by PeterWone** [comment] 2021-12-02 14:23
You might be able to find the CSS file name in `~/.vscode/extensions/pdconsec.vscode-print-0.9.14/node_modules/highlight.js/styles and reference it as per the instructions in the manual for the katex stylesheet, except it's a filesystem reference.

**Comment by isaac-weisberg** [comment] 2022-01-13 07:17
Ahh if only the styling worked out of the box...

**Comment by isaac-weisberg** [comment] 2022-01-25 07:00
@PeterWone Hey, I was wondering, where can I find those changes so that I built the extension myself. And correct me if I'm wrong, does this mean that I will have all the styling that is available in the markdown preview in VSCode already?

**Comment by PeterWone** [comment] 2022-06-17 00:14
@isaac-weisberg after a long hiatus from being crazy busy with my day job I finally have a chance to catch up on issues and PRs. There are problems with styling caused by a workaround for a problem with remote filesystems. I'm going to have to redo the embedded webserver to properly handle dual filesystems, and when that's done I'll revert the styling of HTML to CSS files rather than embed styling into the HTML. That should make things simpler and more predictable from a user perspective.

**Closed** 2022-06-23 14:26 UTC
