### ISSUE TITLE
Problems with formatting

### ISSUE THREAD

**Issue by 18KaiZer71** [PeterWone/vsc-print#33] opened 2019-06-22 16:22 UTC
While using your extension I run into some problem. First and foremost: The print menu won't show up anymore, even after deleting and reinstalling. But the most annyoing part is shown in the pictures below: For some reason parts of the formatting were/are 'destroyed', while exporting the code. I tried printing those parts via a new file, formatting them anew but nothing worked so far. I hope you're able to help me.

<img width="690" alt="Bildschirmfoto 2019-06-22 um 18 01 42" src="https://user-images.githubusercontent.com/52108314/59966208-25a80480-9519-11e9-9bfb-5ad2e1349d10.png">
<img width="472" alt="Bildschirmfoto 2019-06-22 um 18 02 04" src="https://user-images.githubusercontent.com/52108314/59966209-25a80480-9519-11e9-9723-0595c94da089.png">

**Comment by PeterWone** [comment] 2019-06-23 06:58
Thank you for reporting this problem.

Can I have a sample file for which the problem occurs please? To reproduce the problem in my debugger is the first big step.

**Comment by PeterWone** [comment] 2019-06-23 09:56
The formatting inconsistency you are observing is a consequence of mixed spaces and tabs. The renderer _should_ set the CSS tab-size to match your VS Code settings, but just tested this and the value is `undefined`. 

Well done, you have found a bug. I will put out a fix shortly, but I do still need a sample file to help me work out your other issue. In the meantime there is a workaround &mdash; convert all your tabs to spaces. Just set VS Code to use spaces instead of tabs, and then format the document.

**Comment by 18KaiZer71** [comment] 2019-06-23 11:36
Thanks for the fast response. I attached a file with two codes, where the bugs occurred.
[Sample_File.zip](https://github.com/PeterWone/vsc-print/files/3317745/Sample_File.zip)

**Comment by PeterWone** [comment] 2019-06-23 12:54
It appears you are using OS/X. I'll have to borrow a Mac to debug this so it may be a few days before you hear anything.

**Comment by PeterWone** [comment] 2019-06-23 13:53
It took me a while to recognise that language, it's VHDL if I'm not mistaken. None of the VHDL extensions appears to include a formatter so that workaround isn't very practical. And you are right the menu is not appearing for VHDL files. I have manage to reproduce the fault on Windows.

**Comment by PeterWone** [comment] 2019-06-24 01:05
Here's a snip of your sample file with mixed spaces and tabs from 76 to 79. The indent looks wrong because my system is configured for a two-space tab indent, but most of this sample uses four spaces per indent.

![image](https://user-images.githubusercontent.com/5498936/59984587-1a66ed00-966f-11e9-9284-f014cbe12806.png)

**Comment by PeterWone** [comment] 2019-06-24 01:17
_With my current codebase_ I can't reproduce the problem with the print menu not showing up. I suspect this is the same issue reported by issues #31 and #32 which was fixed by 0.7.6, so I'm going to fix the other bug I noticed while chasing yours, and then release 0.7.7

**Comment by PeterWone** [comment] 2019-06-24 04:18
Set your tab size to 4 and update your copy of vscode-print.

Please let me know that you are satisfied with this fix by closing the issue.

**Comment by 18KaiZer71** [comment] 2019-06-24 14:34
Thank you, for your fast response and fix. I apologize for replying so late. Formatting works like a charm now. One last problem I run into (don't know whether its MAC exclusive or not or a 'feature'): if I try selecting a theme via the the option F1 -> Printing: Browse for stylesheets I get the following error (the paths seem to be wrong?). Selecting the file manually (writing the name of the theme into the setting 'Print: Colour Scheme')
[error.pdf](https://github.com/PeterWone/vsc-print/files/3321295/error.pdf)
 works.

**Comment by PeterWone** [comment] 2019-06-24 21:54
That’s incompatibility with the Mac file structure – not the file system itself, the layout of VS Code and its extensions.  I’ll have to get a Mac and do some testing and debugging, unless you are willing to do it and file a pull request, in which case I would be delighted to incorporate your changes.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by PeterWone** [comment] 2019-06-24 22:07
I'm closing this issue and opening a new one with the path problem.

**Closed by PeterWone** 2019-06-24 22:07 UTC
