### ISSUE TITLE
Image Support

### ISSUE THREAD

**Issue by ac-webdesign** [PeterWone/vsc-print#22] opened 2019-04-25 13:49 UTC
Actually when you print a markdown with a image, it only shown the alternate text of the image:
![image](https://user-images.githubusercontent.com/43271236/56740338-0dae4180-6771-11e9-9214-415bc590d93a.png)

Convert vsc.print it first to a pdf?
Have anybody already an idea?

**Comment by PeterWone** [comment] 2019-04-26 06:46
I recently changed rendering engines. I will have to re-test this.

**Comment by PeterWone** [comment] 2019-04-26 12:29
It works when I print VSC-print's own readme.md so I guess there must be some special case that you are experiencing. Can I have a sample document that produces the problem? If the sample also demonstrates the extended character set issue that would be good because I've made the change for #21 and I would like to test but I don't have any documents suitable for testing.

**Comment by ac-webdesign** [comment] 2019-04-26 12:56
Here I create a Zip with my tests. I put everything in one README.
[vsc-print-issue-21-22.zip](https://github.com/PeterWone/vsc-print/files/3121370/vsc-print-issue-21-22.zip)

**Comment by PeterWone** [comment] 2019-04-26 13:28
The good news: extended character set problem is solved, and I can reproduce the image problem. The bad news: there is a problem with local paths for images. I have an idea of how to solve the use of images on local paths but I will not have time to make the changes today.

While you wait for me to support local image paths, you can work around this problem by putting your images on an image service like imgur.com and using a fully qualified URL.

**Comment by ac-webdesign** [comment] 2019-04-26 14:46
@PeterWone Great. Thanks for eveything.

**Comment by PeterWone** [comment] 2019-04-26 22:37
I have extended the embedded webserver to handle requests for image files with relative paths in the file system. There is no protection against malicious backpathing by a document because requests to the embedded webserver only work for local processes (unless you set up port forwarding in your firewall, but people who know _how_ to do that would be aware of the danger).

It's working, but oversize images are causing layout and page break problems. I'll commit this and post a new release after I make some CSS tweaks to limit image width to 100% of page width.

**Comment by PeterWone** [comment] 2019-04-26 23:00
The scaling problem occurs only with browsers based on the Chromium engine. FireFox and Edge correctly handle max-width, Chrome and Edge Dev do not. This is unfortunate since only Chromium based browsers close after printing.

I am looking for a workaround for max-width with Chrome. Since you're a web developer, this problem is squarely within your expertise so perhaps you can assist.

**Comment by PeterWone** [comment] 2019-04-27 07:39
It seems I have unfairly impugned Chromium, I applied max-width:100% to `image` when it should have been `img`. Correcting this fixes the layout problem. I still say this should be the default, but that's a much milder bug than not honouring it at all. So anway, it's fixed and I'm closing both these issues and rolling out 0.6.9

**Closed by PeterWone** 2019-04-27 07:39 UTC

**Comment by ac-webdesign** [comment] 2019-04-27 15:30
@PeterWone Thanks for the changes and for mentioned in the ReadMe.md

**Comment by PeterWone** [comment] 2019-04-27 21:29
After you have used it for long enough to decide whether you like it,  please consider writing a review on the marketplace, in your preferred language if you think other Swiss would like to see that.

**Comment by ac-webdesign** [comment] 2019-07-02 06:13
@PeterWone After the new changes `Version 0.7.8` the image support doesn't work anymore? Can you explain why?
![image](https://user-images.githubusercontent.com/43271236/60488048-325af400-9ca1-11e9-9c2c-9d610107eae7.png)

**Comment by PeterWone** [comment] 2019-07-02 08:17
I will open a new issue and investigate. Apologies for the inconvenience.

**Comment by PeterWone** [comment] 2019-07-02 11:23
Please let me know in #37 whether 0.7.9 resolves the problem.

**Comment by PeterWone** [comment] 2019-10-11 01:21
I haven't made any changes for some time now, I'll re-run with the test pages you gave me last time.
